CREATE TABLE `jibres_XXXXXXX`.`factors` (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`type` ENUM('sale','buy','presell','lending','backbuy','backsell','waste','saleorder') CHARACTER SET utf8mb4 NOT NULL,
`customer` int(10) UNSIGNED DEFAULT NULL,
`seller` int(10) unsigned NULL DEFAULT NULL,
`date` timestamp NULL,
`qty` DECIMAL(19, 4) DEFAULT NULL,
`subprice` DECIMAL(31,4) NULL DEFAULT NULL,
`subtotal` DECIMAL(31, 4) NULL DEFAULT NULL,
`subvat` DECIMAL(31, 4) NULL DEFAULT NULL,
`subdiscount` DECIMAL(31, 4) NULL DEFAULT NULL,
`discount` DECIMAL(22, 4) DEFAULT NULL,
`discount2` DECIMAL(22, 4) DEFAULT NULL,
`shipping` DECIMAL(13, 4) NULL DEFAULT NULL,
`shippingvat` DECIMAL(13, 4) NULL DEFAULT NULL,
`total` DECIMAL(31, 4) NULL DEFAULT NULL,
`title` varchar(500) DEFAULT NULL,
`item` bigint(20) UNSIGNED DEFAULT NULL,
`pre` bit(1) DEFAULT NULL,
`address_id` bigint(20) UNSIGNED DEFAULT NULL,
`status` ENUM('draft','registered','awaiting','confirmed','cancel','expire','preparing','sending','delivered','revert','success','complete','archive','deleted','spam') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`datecreated` timestamp DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc` text CHARACTER SET utf8mb4,
`guestid` varchar(50) CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`mode` ENUM('admin', 'customer', 'auto') DEFAULT NULL,
`paystatus` ENUM('awaiting_payment','awaiting_verify_payment','unsuccessful_payment','payment_unverified','successful_payment') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `factors_index_qty` (`qty`),
KEY `factors_index_total` (`total`),
KEY `index_search_type` (`type`),
KEY `index_search_item` (`item`),
KEY `index_search_date` (`date`),
KEY `index_search_status` (`status`),
KEY `factors_index_discount` (`discount`),
KEY `factors_index_discount2` (`discount2`),
KEY `factors_index_shipping` (`shipping`),
KEY `factors_index_subvat` (`subvat`),
KEY `factors_index_subprice` (`subprice`),
KEY `factors_index_subdiscount` (`subdiscount`),
KEY `factors_index_subtotal` (`subtotal`),
KEY `factors_index_paystatus` (`paystatus`),
CONSTRAINT `factors_customer` FOREIGN KEY (`seller`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `factors_address_id` FOREIGN KEY (`address_id`) REFERENCES `address` (`id`) ON UPDATE CASCADE,
CONSTRAINT `factors_seller` FOREIGN KEY (`customer`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
