CREATE TABLE `jibres_XXXXXXX`.`products` (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`title` varchar(500) DEFAULT NULL,
`seotitle` varchar(300) DEFAULT NULL,
`slug` varchar(200) DEFAULT NULL,

`finalprice` bigint(20) DEFAULT NULL,
`vatprice` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`discountpercent` int(10) DEFAULT NULL,
`discount` bigint(20) DEFAULT NULL,
`compareatprice` bigint(20) UNSIGNED DEFAULT NULL,
`price` bigint(20) UNSIGNED DEFAULT NULL,
`buyprice` bigint(20) UNSIGNED DEFAULT NULL,

`seodesc` varchar(500) DEFAULT NULL,
`desc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
`barcode` varchar(100) DEFAULT NULL,
`barcode2` varchar(100) DEFAULT NULL,
`cat_id` int(10) UNSIGNED DEFAULT NULL,
`unit_id` int(10) UNSIGNED DEFAULT NULL,
`company_id` int(10) UNSIGNED DEFAULT NULL,
`sku` varchar(20) DEFAULT NULL,
`salestep` int(10) UNSIGNED DEFAULT NULL,
`minstock` int(10) UNSIGNED DEFAULT NULL,
`maxstock` int(10) UNSIGNED DEFAULT NULL,
`minsale` int(10) UNSIGNED DEFAULT NULL,
`maxsale` int(10) UNSIGNED DEFAULT NULL,
`carton` int(10) UNSIGNED DEFAULT NULL,
`scalecode` int(10) DEFAULT NULL,
`weight` int(10) DEFAULT NULL,
`length` int(10) DEFAULT NULL,
`width` int(10) DEFAULT NULL,
`height` int(10) DEFAULT NULL,
`filesize` int(10) DEFAULT NULL,
`fileaddress` varchar(500) DEFAULT NULL,
`type` enum('product','file','service') NOT NULL DEFAULT 'product',
`status` enum('unset','available','unavailable','soon','discountinued','deleted') DEFAULT NULL,
`thumb` varchar(500) DEFAULT NULL,
`gallery` text,
`vat` enum('yes', 'no') DEFAULT NULL,
`infinite` enum('yes', 'no') DEFAULT NULL,
`oversale` enum('yes', 'no') DEFAULT NULL,
`saleonline` enum('yes', 'no') DEFAULT NULL,
`saletelegram` enum('yes', 'no') DEFAULT NULL,
`saleapp` enum('yes', 'no') DEFAULT NULL,
`variants` mediumtext CHARACTER SET utf8mb4,
`variant_child` bit(1) NULL DEFAULT NULL,
`optionname1` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`optionname2` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`optionname3` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`optionvalue1` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`optionvalue2` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`optionvalue3` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`parent` int(10) UNSIGNED DEFAULT NULL,
`datecreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
CONSTRAINT `products_field_company_id` FOREIGN KEY (`company_id`) REFERENCES `productcompany` (`id`) ON UPDATE CASCADE,
CONSTRAINT `products_field_unit_id` FOREIGN KEY (`unit_id`) REFERENCES `productunit` (`id`) ON UPDATE CASCADE,
KEY `index_search_products_sku` (`sku`),
KEY `index_search_products_title` (`title`),
KEY `index_search_products_parent` (`parent`),
KEY `index_search_products_status` (`status`),
KEY `index_search_products_barcode` (`barcode`),
KEY `index_search_products_saleapp` (`saleapp`),
KEY `index_search_products_barcode2` (`barcode2`),
KEY `index_search_products_scalecode` (`scalecode`),
KEY `index_search_products_optionname1` (`optionname1`),
KEY `index_search_products_optionname2` (`optionname2`),
KEY `index_search_products_optionname3` (`optionname3`),
KEY `index_search_products_optionvalue1` (`optionvalue1`),
KEY `index_search_products_optionvalue2` (`optionvalue2`),
KEY `index_search_products_optionvalue3` (`optionvalue3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;