CREATE TABLE `jibres_XXXXXXX`.`users` (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`jibres_user_id` int(10) UNSIGNED NULL,
`username` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`displayname` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`gender` enum('male','female','company','rather not say') DEFAULT NULL,
`password` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
`title` varchar(100) DEFAULT NULL,
`mobile` varchar(15) DEFAULT NULL,
`verifymobile` bit(1) DEFAULT NULL,
`email` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`verifyemail` bit(1) DEFAULT NULL,
`status` ENUM('active','awaiting','deactive','removed','filter','unreachable','ban','block') CHARACTER SET utf8mb4  NULL DEFAULT 'awaiting',
`avatar` varchar(2000) CHARACTER SET utf8mb4 DEFAULT NULL,
`parent` int(10) UNSIGNED DEFAULT NULL,
`permission` varchar(200) DEFAULT NULL,
`type` varchar(100) DEFAULT NULL,
`datecreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`pin` smallint(4) UNSIGNED DEFAULT NULL,
`ref` int(10) UNSIGNED DEFAULT NULL,
`twostep` bit(1) DEFAULT NULL,
`subscribe` bit(1) DEFAULT NULL,
`birthday` varchar(50) DEFAULT NULL,
`unit_id` smallint(5) DEFAULT NULL,
`language` char(2) DEFAULT NULL,
`meta` mediumtext CHARACTER SET utf8mb4,
`website` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`facebook` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`twitter` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`instagram` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`linkedin` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`gmail` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`sidebar` bit(1) DEFAULT NULL,
`theme` varchar(100) DEFAULT NULL,
`firstname` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`lastname` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`bio` text CHARACTER SET utf8mb4,
`forceremember` bit(1) DEFAULT NULL,
`signature` text CHARACTER SET utf8mb4,
`father` varchar(100) DEFAULT NULL,
`nationalcode` varchar(50) DEFAULT NULL,
`nationality` varchar(5) DEFAULT NULL,
`pasportcode` varchar(50) DEFAULT NULL,
`pasportdate` varchar(20) DEFAULT NULL,
`marital` enum('single','married') DEFAULT NULL,
`foreign` bit(1) DEFAULT NULL,
`phone` varchar(100) DEFAULT NULL,
`detail` text CHARACTER SET utf8mb4,
`ban_expire` datetime NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `index_search_jibres_user_id` (`jibres_user_id`),
KEY `index_search_mobile` (`mobile`),
KEY `index_search_nationalcode` (`nationalcode`),
KEY `index_search_pasportcode` (`pasportcode`),
KEY `index_search_email` (`email`),
KEY `index_search_username` (`username`),
KEY `index_search_permission` (`permission`),
KEY `index_search_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;