CREATE TABLE `jibres_XXXXXXX`.`productterms` (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`type` enum('cat','tag','code','other','term') DEFAULT NULL,
`title` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
`slug` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
`url` varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL,
`order` smallint(5) UNSIGNED DEFAULT NULL,
`desc` mediumtext CHARACTER SET utf8mb4,
`meta` mediumtext CHARACTER SET utf8mb4,
`parent` int(10) UNSIGNED DEFAULT NULL,
`creator` int(10) UNSIGNED DEFAULT NULL,
`status` enum('enable','disable','delete') NOT NULL DEFAULT 'enable',
`count` int(10) UNSIGNED DEFAULT NULL,
`site` enum('yes','no') NOT NULL DEFAULT 'yes',
`valuetype` enum('decimal','integer') DEFAULT NULL,
`isdefault` bit(1) DEFAULT NULL,
`file` varchar(1000) DEFAULT NULL,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`datecreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`defaultproperty` text CHARACTER SET utf8mb4,
 PRIMARY KEY (`id`),
 KEY `terms_type_search_index` (`type`),
 CONSTRAINT `productterms_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;