CREATE TABLE `jibres_XXXXXXX`.`factors` (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`type` enum('sale','buy','presell','lending','backbuy','backsell','waste') NOT NULL,
`customer` int(10) UNSIGNED DEFAULT NULL,
`seller` int(10) UNSIGNED NOT NULL,
`date` timestamp NULL,
`title` varchar(500) DEFAULT NULL,
`qty` int(10) UNSIGNED DEFAULT NULL,
`item` bigint(20) UNSIGNED DEFAULT NULL,
`subprice` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`subdiscount` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`subtotal` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`subvat` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`discount` int(10) DEFAULT NULL,
`discount2` int(10) DEFAULT NULL,
`pre` bit(1) DEFAULT NULL,
`shipping` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
 `shippingvat` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`total` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`pay` bit(1) DEFAULT NULL,
`address_id` bigint(20) UNSIGNED DEFAULT NULL,
`status` enum('enable','disable','expire','draft','deleted') NOT NULL DEFAULT 'draft',
`datecreated` timestamp DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc` text CHARACTER SET utf8mb4,
PRIMARY KEY (`id`),
KEY `index_search_qty` (`qty`),
KEY `index_search_sum` (`total`),
KEY `index_search_type` (`type`),
KEY `index_search_item` (`item`),
KEY `index_search_date` (`date`),
KEY `index_search_status` (`status`),
KEY `index_search_discount` (`discount`),
KEY `index_search_detailsum` (`subprice`),
KEY `index_search_detaildiscount` (`subdiscount`),
KEY `index_search_detailtotalsum` (`subtotal`),
CONSTRAINT `factors_customer` FOREIGN KEY (`seller`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `factors_address_id` FOREIGN KEY (`address_id`) REFERENCES `address` (`id`) ON UPDATE CASCADE,
CONSTRAINT `factors_seller` FOREIGN KEY (`customer`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;