CREATE TABLE `jibres_XXXXXXX`.`factors` (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`type` enum('sale','buy','presell','lending','backbuy','backsell','waste') NOT NULL,
`customer` int(10) UNSIGNED DEFAULT NULL,
`seller` int(10) UNSIGNED NOT NULL,
`date` datetime NOT NULL,
`title` varchar(500) DEFAULT NULL,
`pre` bit(1) DEFAULT NULL,
`transport` bigint(20) UNSIGNED DEFAULT NULL,
`pay` bit(1) DEFAULT NULL,
`detailsum` bigint(20) UNSIGNED DEFAULT NULL,
`detaildiscount` bigint(20) DEFAULT NULL,
`detailtotalsum` bigint(20) UNSIGNED DEFAULT NULL,
`qty` float UNSIGNED DEFAULT NULL,
`vat` int(10) UNSIGNED DEFAULT NULL,
`discount` int(10) DEFAULT NULL,
`sum` bigint(20) UNSIGNED DEFAULT NULL,
`status` enum('enable','disable','expire','draft','deleted') NOT NULL DEFAULT 'draft',
`datecreated` datetime DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc` text CHARACTER SET utf8mb4,
`discount2` int(10) DEFAULT NULL,
`item` bigint(20) UNSIGNED DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `index_search_qty` (`qty`),
KEY `index_search_sum` (`sum`),
KEY `index_search_pay` (`pay`),
KEY `index_search_type` (`type`),
KEY `index_search_item` (`item`),
KEY `index_search_date` (`date`),
KEY `index_search_seller` (`seller`),
KEY `index_search_status` (`status`),
KEY `index_search_customer` (`customer`),
KEY `index_search_discount` (`discount`),
KEY `index_search_discount2` (`discount2`),
KEY `index_search_detailsum` (`detailsum`),
KEY `index_search_detaildiscount` (`detaildiscount`),
KEY `index_search_detailtotalsum` (`detailtotalsum`),
CONSTRAINT `factors_customer` FOREIGN KEY (`seller`) REFERENCES `userstore` (`id`) ON UPDATE CASCADE,
CONSTRAINT `factors_seller` FOREIGN KEY (`customer`) REFERENCES `userstore` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

