CREATE TABLE IF NOT EXISTS `jibres_XXXXXXX`.`posts` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `language` char(2) DEFAULT NULL,
  `title` VARCHAR(255) CHARACTER SET utf8mb4 NULL,
  `seotitle` varchar(500) DEFAULT NULL,
  `slug` VARCHAR(100) CHARACTER SET utf8mb4 NULL,
  `url` varchar(190) CHARACTER SET utf8mb4 DEFAULT NULL,
  `content` mediumtext CHARACTER SET utf8mb4,
  `thumb` varchar(500) NULL DEFAULT NULL,
  `cover` varchar(500) NULL DEFAULT NULL,
  `gallery` TEXT NULL DEFAULT NULL,
  `subtitle` varchar(500) CHARACTER SET utf8mb4 DEFAULT NULL,
  `excerpt` varchar(500) CHARACTER SET utf8mb4 DEFAULT NULL,
  `meta` mediumtext CHARACTER SET utf8mb4,
  `subtype` enum('standard', 'gallery','video','audio') NULL DEFAULT 'standard',
  `type` varchar(100) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'post',
  `special` varchar(100) DEFAULT NULL,
  `comment` ENUM('open','closed','default') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
  `seorank` smallint(3) NULL DEFAULT NULL,
  `showwriter` ENUM('visible','hidden','default') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
  `showdate` ENUM('visible','hidden','default') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
  `status` ENUM('publish','draft','deleted','pending_review') CHARACTER SET utf8mb4 NOT NULL DEFAULT 'draft',
  `parent` bigint(20) UNSIGNED DEFAULT NULL,
  `user_id` int(10) UNSIGNED NOT NULL,
  `publishdate` datetime DEFAULT NULL,
  `datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `datecreated` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `redirecturl` text CHARACTER SET utf8mb4 NULL,
  `specialaddress` enum('independence', 'special', 'under_tag', 'under_page')  NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `posts_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
  UNIQUE KEY `url_unique` (`url`,`language`) USING BTREE,
  KEY `index_search_status` (`status`),
  KEY `index_search_type` (`type`),
  KEY `index_search_language` (`language`),
  KEY `index_search_publishdate` (`publishdate`),
  KEY `search_index_subtype` (`subtype`),
  KEY `index_search_url` (`url`),
  KEY `index_search_slug` (`slug`),
  KEY `posts_index_search_seorank` (`seorank`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;