<?php
namespace content_site\template\site;


class demo_001
{
	public static function detail()
	{
		return
		[
			'key'   => 'demo_001',
			'title' => T_("Demo 001"),
			'category' => 'category1',

		];
	}

	public static function records()
	{
		return
		[
			[
				'use_as_logo'                   => 'business_logo',
				'use_as_heading'                => 'business_heading',
				'menu_1'                        => 1,
				'link_search'                   => true,
				'link_enter'                    => true,
				'link_cart'                     => true,
				'heading_position'              => null,
				'heading'                       => null,
				'container'                     => 'xl',
				'_mode'                         => null,
				'_folder'                       => 'header',
				'_section'                      => 'header',
				'_model'                        => 'h3',
				'_preview_key'                  => 'p1',
			],
			[
				'radius'                        => '3xl',
				'magicbox_title_position'       => 'hide',
				'magicbox_gap'                  => 'md',
				'link_color'                    => 'inside',
				'image_count'                   => 1,
				'height'                        => 'sm',
				'effect'                        => 'zoom',
				'coverratio'                    => 'free',
				'container'                     => 'xl',
				'background_pack'               => 'none',
				'_mode'                         => null,
				'_folder'                       => 'body',
				'_section'                      => 'gallery',
				'_model'                        => 'g1',
				'_preview_key'                  => 'p2',
			],
			[
				'radius_normal'                 => 'none',
				'radius'                        => 'lg',
				'post_template'                 => 'any',
				'post_show_readingtime'         => true,
				'post_show_image'               => true,
				'post_show_excerpt'             => true,
				'post_show_date'                => 'relative',
				'post_show_author'              => true,
				'post_order'                    => 'latest',
				'height'                        => 'md',
				'heading_position'              => 'center',
				'heading'                       => 'Latest Posts',
				'coverratio'                    => '16:9',
				'count'                         => 3,
				'color_text'                    => '#333333',
				'btn_viewall_mode'              => 'dark',
				'btn_viewall_check'             => true,
				'btn_viewall'                   => T_("View all"),
				'background_pack'               => 'none',
				'_mode'                         => null,
				'_folder'                       => 'body',
				'_section'                      => 'blog',
				'_model'                        => 'b1',
				'_preview_key'                  => 'p1',
			],
			[
				'use_as_socialnetwork'          => 'business_socialnetwork',
				'use_as_logo'                   => 'business_logo',
				'use_as_heading'                => 'business_heading',
				'use_as_description'            => 'business_description',
				'radius'                        => 'full',
				'height'                        => 30,
				'heading'                       => 'Visit card',
				'background_pack'               => 'solid',
				'background_color'              => '#eeeeee',
				'_mode'                         => null,
				'_folder'                       => 'body',
				'_section'                      => 'visitcard',
				'_model'                        => 'visitcard1',
				'_preview_key'                  => 'p1',
			],
			[
				'_mode'                         => null,
				'_folder'                       => 'body',
				'_section'                      => 'separator',
				'_model'                        => 'separator1',
				'_preview_key'                  => 'p1',
			],
			[
				'radius'                        => 'lg',
				'product_show_title'            => true,
				'product_show_price'            => true,
				'product_order'                 => 'newest',
				'magicbox_title_position'       => 'inside',
				'magicbox_gap'                  => 'sm',
				'link_color_magicbox_title'     => 'light',
				'link_color'                    => 'light',
				'height'                        => 'sm',
				'heading_position'              => 'center',
				'heading'                       => 'Latest Posts',
				'effect'                        => 'dark',
				'coverratio'                    => '16:9',
				'count'                         => 12,
				'color_text'                    => '#333333',
				'btn_viewall_mode'              => 'dark',
				'btn_viewall_check'             => true,
				'btn_viewall'                   => T_("View all"),
				'background_pack'               => 'none',
				'_mode'                         => null,
				'_folder'                       => 'body',
				'_section'                      => 'product',
				'_model'                        => 'p2',
				'_preview_key'                  => 'p1',
			],
			[
				'use_as_description'            => null,
				'height'                        => 'fullscreen',
				'heading'                       => 'Coming Soon',
				'container_justify'             => 'left',
				'container_align'               => 'end',
				'color_text'                    => '#ffffff',
				'color_heading'                 => '#ffffff',
				'background_pack'               => 'image',
				'background_image'              => 'https://cdn.jibres.local/business/comingsoon-1/img/jibres-soon-1.jpg',
				'background_effect'             => 'mesh',
				'_mode'                         => null,
				'_folder'                       => 'body',
				'_section'                      => 'headline',
				'_model'                        => 'headline1',
				'_preview_key'                  => 'p1',
			],
			[
				'use_as_heading'                => 'business_heading',
				'use_as_footer_link'            => 'default',
				'_mode'                         => null,
				'_folder'                       => 'footer',
				'_section'                      => 'footer',
				'_model'                        => 'f1',
				'_preview_key'                  => 'p1',
			],
		];
	}
}
?>