CREATE TABLE `address` (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id` int(10) UNSIGNED NOT NULL,
`subdomain` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`title` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`firstname` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`lastname` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`company` bit(1) DEFAULT NULL,
`companyname` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`jobtitle` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`country` char(2) CHARACTER SET utf8mb4 DEFAULT NULL,
`province` varchar(6) CHARACTER SET utf8mb4 DEFAULT NULL,
`city` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`address` varchar(500) CHARACTER SET utf8mb4 DEFAULT NULL,
`address2` varchar(500) CHARACTER SET utf8mb4 DEFAULT NULL,
`postcode` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
`phone` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
`fax` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
`status` enum('enable','disable','filter','leave','spam','delete') NULL DEFAULT 'enable',
`favorite` bit(1) DEFAULT NULL,
`isdefault` bit(1) DEFAULT NULL,
`latitude` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`longitude` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`map` text CHARACTER SET utf8mb4 DEFAULT NULL,
`datecreated` timestamp DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
CONSTRAINT `address_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
