INSERT INTO jibres.business_domain
(
  `domain`,
  `domain_id`,
  `store_id`,
  `user_id`,
  `subdomain`,
  `root`,
  `tld`,
  `master`,
  `redirecttomaster`,
  `cdn`,
  `status`,
  `checkdns`,
  `cdnpanel`,
  `httpsrequest`,
  `httpsverify`,
  `datecreated`,
  `datemodified`,
  `dnsok`
)
SELECT
	jibres.store_domain.domain,
	NULL,
	jibres.store_domain.store_id,
	jibres.store_domain.user_id,
	jibres.store_domain.subdomain,
	jibres.store_domain.root,
	jibres.store_domain.tld,
	jibres.store_domain.master,
	NULL,
	'arvancloud',
	'pending',
	NULL,
	NULL,
	NULL,
	NULL,
	jibres.store_domain.datecreated,
	jibres.store_domain.datemodified,
	NULL
FROM
	jibres.store_domain
WHERE 1;