CREATE TABLE jibres.changelog (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`language` CHAR(2) NULL DEFAULT NULL,
`date` date NULL DEFAULT NULL,
`title` text NULL DEFAULT NULL,
`link` text NULL DEFAULT NULL,
`user_id` int(10) UNSIGNED NULL DEFAULT NULL,
`tag1` varchar(50) NULL DEFAULT NULL,
`tag2` varchar(50) NULL DEFAULT NULL,
`tag3` varchar(50) NULL DEFAULT NULL,
`tag4` varchar(50) NULL DEFAULT NULL,
`tag5` varchar(50) NULL DEFAULT NULL,
`version` varchar(100) NULL DEFAULT NULL,
`datecreated` timestamp NULL DEFAULT NULL,
`datemodified` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `index_search_changelog_date` (`date`),
KEY `index_search_changelog_language` (`language`),
KEY `index_search_changelog_tag1` (`tag1`),
KEY `index_search_changelog_tag2` (`tag2`),
KEY `index_search_changelog_tag3` (`tag3`),
KEY `index_search_changelog_tag4` (`tag4`),
KEY `index_search_changelog_tag5` (`tag5`),
KEY `index_search_changelog_version` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;