CREATE TABLE IF NOT EXISTS jibres_api_log.kavenegar (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`mobile` varchar(50) NULL DEFAULT NULL,
`mobiles` text NULL DEFAULT NULL,
`message` text NULL DEFAULT NULL,
`urlmd5` CHAR(32) NULL,
`url` text NULL,
`mode` enum('sms', 'call','tts') NULL,
`type` enum('signup', 'login','twostep', 'twostepset', 'twostepunset', 'deleteaccount', 'recovermobile', 'callback_signup', 'changepassword', 'notif', 'other') NULL,
`user_id` int(10) UNSIGNED NULL,
`ip` VARCHAR(200) NULL,
`store_id` int(10) UNSIGNED NULL,
`ip_id` int(10) UNSIGNED NULL,
`ip_md5` CHAR(32) NULL,
`agent_id` int(10) UNSIGNED NULL,
`line` varchar(100) NULL DEFAULT NULL,
`apikey` text NULL DEFAULT NULL,
`response` text NULL DEFAULT NULL,
`send` text NULL DEFAULT NULL,
`datesend` timestamp NULL,
`dateresponse` timestamp NULL,
`datecreated` timestamp NULL,
`datemodified` timestamp NULL,
PRIMARY KEY (`id`),
KEY `jibres_api_log_kavenegar_mobile` (`mobile`),
KEY `jibres_api_log_kavenegar_urlmd5` (`urlmd5`),
KEY `jibres_api_log_kavenegar_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;