CREATE TABLE jibres.portfolio (
`id` int UNSIGNED NOT NULL AUTO_INCREMENT,
`language` CHAR(2) NULL DEFAULT NULL,
`title` varchar(300) NULL DEFAULT NULL,
`industry` varchar(200) NULL DEFAULT NULL,
`desc` text NULL DEFAULT NULL,
`store_id` bigint NULL DEFAULT NULL,
`sort` int NULL DEFAULT NULL,
`url` text NULL DEFAULT NULL,
`status` enum('request', 'accept', 'reject', 'delete') NULL DEFAULT NULL,
`tag1` varchar(50) NULL DEFAULT NULL,
`tag2` varchar(50) NULL DEFAULT NULL,
`tag3` varchar(50) NULL DEFAULT NULL,
`tag4` varchar(50) NULL DEFAULT NULL,
`tag5` varchar(50) NULL DEFAULT NULL,
`thumb` text NULL DEFAULT NULL,
`image` text NULL DEFAULT NULL,
`datecreated` timestamp NULL DEFAULT NULL,
`datemodified` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `index_search_portfolio_sort` (`sort`),
KEY `index_search_portfolio_language` (`language`),
KEY `index_search_portfolio_title` (`title`),
KEY `index_search_portfolio_tag1` (`tag1`),
KEY `index_search_portfolio_tag2` (`tag2`),
KEY `index_search_portfolio_tag3` (`tag3`),
KEY `index_search_portfolio_tag4` (`tag4`),
KEY `index_search_portfolio_tag5` (`tag5`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;