<?php
namespace lib;

class currncy {

	public static function list()
	{
		$currncy =
		[
			"USD" => ["symbol" => "$", 		"decimal_digits" => 2, "code" => "USD", "name" => "US Dollar", "symbol_native" => "$", "name_plural" => "US dollars", ],
			"CAD" => ["symbol" => "CA$", 	"decimal_digits" => 2, "code" => "CAD", "name" => "Canadian Dollar", "symbol_native" => "$", "name_plural" => "Canadian dollars", ],
			"EUR" => ["symbol" => "€", 		"decimal_digits" => 2, "code" => "EUR", "name" => "Euro", "symbol_native" => "€", "name_plural" => "euros", ],
			"AED" => ["symbol" => "AED", 	"decimal_digits" => 2, "code" => "AED", "name" => "United Arab Emirates Dirham", "symbol_native" => "د.إ.‏", "name_plural" => "UAE dirhams", ],
			"AFN" => ["symbol" => "Af", 	"decimal_digits" => 0, "code" => "AFN", "name" => "Afghan Afghani", "symbol_native" => "؋", "name_plural" => "Afghan Afghanis", ],
			"ALL" => ["symbol" => "ALL", 	"decimal_digits" => 0, "code" => "ALL", "name" => "Albanian Lek", "symbol_native" => "Lek", "name_plural" => "Albanian lekë", ],
			"AMD" => ["symbol" => "AMD", 	"decimal_digits" => 0, "code" => "AMD", "name" => "Armenian Dram", "symbol_native" => "դր.", "name_plural" => "Armenian drams", ],
			"ARS" => ["symbol" => "AR$", 	"decimal_digits" => 2, "code" => "ARS", "name" => "Argentine Peso", "symbol_native" => "$", "name_plural" => "Argentine pesos", ],
			"AUD" => ["symbol" => "AU$", 	"decimal_digits" => 2, "code" => "AUD", "name" => "Australian Dollar", "symbol_native" => "$", "name_plural" => "Australian dollars", ],
			"AZN" => ["symbol" => "man.", 	"decimal_digits" => 2, "code" => "AZN", "name" => "Azerbaijani Manat", "symbol_native" => "ман.", "name_plural" => "Azerbaijani manats", ],
			"BAM" => ["symbol" => "KM", 	"decimal_digits" => 2, "code" => "BAM", "name" => "Bosnia-Herzegovina Convertible Mark", "symbol_native" => "KM", "name_plural" => "Bosnia-Herzegovina convertible marks", ],
			"BDT" => ["symbol" => "Tk", 	"decimal_digits" => 2, "code" => "BDT", "name" => "Bangladeshi Taka", "symbol_native" => "৳", "name_plural" => "Bangladeshi takas", ],
			"BGN" => ["symbol" => "BGN", 	"decimal_digits" => 2, "code" => "BGN", "name" => "Bulgarian Lev", "symbol_native" => "лв.", "name_plural" => "Bulgarian leva", ],
			"BHD" => ["symbol" => "BD", 	"decimal_digits" => 3, "code" => "BHD", "name" => "Bahraini Dinar", "symbol_native" => "د.ب.‏", "name_plural" => "Bahraini dinars", ],
			"BIF" => ["symbol" => "FBu", 	"decimal_digits" => 0, "code" => "BIF", "name" => "Burundian Franc", "symbol_native" => "FBu", "name_plural" => "Burundian francs", ],
			"BND" => ["symbol" => "BN$", 	"decimal_digits" => 2, "code" => "BND", "name" => "Brunei Dollar", "symbol_native" => "$", "name_plural" => "Brunei dollars", ],
			"BOB" => ["symbol" => "Bs", 	"decimal_digits" => 2, "code" => "BOB", "name" => "Bolivian Boliviano", "symbol_native" => "Bs", "name_plural" => "Bolivian bolivianos", ],
			"BRL" => ["symbol" => "R$", 	"decimal_digits" => 2, "code" => "BRL", "name" => "Brazilian Real", "symbol_native" => "R$", "name_plural" => "Brazilian reals", ],
			"BWP" => ["symbol" => "BWP", 	"decimal_digits" => 2, "code" => "BWP", "name" => "Botswanan Pula", "symbol_native" => "P", "name_plural" => "Botswanan pulas", ],
			"BYR" => ["symbol" => "BYR", 	"decimal_digits" => 0, "code" => "BYR", "name" => "Belarusian Ruble", "symbol_native" => "BYR", "name_plural" => "Belarusian rubles", ],
			"BZD" => ["symbol" => "BZ$", 	"decimal_digits" => 2, "code" => "BZD", "name" => "Belize Dollar", "symbol_native" => "$", "name_plural" => "Belize dollars", ],
			"CDF" => ["symbol" => "CDF", 	"decimal_digits" => 2, "code" => "CDF", "name" => "Congolese Franc", "symbol_native" => "FrCD", "name_plural" => "Congolese francs", ],
			"CHF" => ["symbol" => "CHF", 	"decimal_digits" => 2, "code" => "CHF", "name" => "Swiss Franc", "symbol_native" => "CHF", "name_plural" => "Swiss francs", "rounding" => 0.05],
			"CLP" => ["symbol" => "CL$", 	"decimal_digits" => 0, "code" => "CLP", "name" => "Chilean Peso", "symbol_native" => "$", "name_plural" => "Chilean pesos", ],
			"CNY" => ["symbol" => "CN¥", 	"decimal_digits" => 2, "code" => "CNY", "name" => "Chinese Yuan", "symbol_native" => "CN¥", "name_plural" => "Chinese yuan", ],
			"COP" => ["symbol" => "CO$", 	"decimal_digits" => 0, "code" => "COP", "name" => "Colombian Peso", "symbol_native" => "$", "name_plural" => "Colombian pesos", ],
			"CRC" => ["symbol" => "₡", 		"decimal_digits" => 0, "code" => "CRC", "name" => "Costa Rican Colón", "symbol_native" => "₡", "name_plural" => "Costa Rican colóns", ],
			"CVE" => ["symbol" => "CV$", 	"decimal_digits" => 2, "code" => "CVE", "name" => "Cape Verdean Escudo", "symbol_native" => "CV$", "name_plural" => "Cape Verdean escudos", ],
			"CZK" => ["symbol" => "Kč", 	"decimal_digits" => 2, "code" => "CZK", "name" => "Czech Republic Koruna", "symbol_native" => "Kč", "name_plural" => "Czech Republic korunas", ],
			"DJF" => ["symbol" => "Fdj", 	"decimal_digits" => 0, "code" => "DJF", "name" => "Djiboutian Franc", "symbol_native" => "Fdj", "name_plural" => "Djiboutian francs", ],
			"DKK" => ["symbol" => "Dkr", 	"decimal_digits" => 2, "code" => "DKK", "name" => "Danish Krone", "symbol_native" => "kr", "name_plural" => "Danish kroner", ],
			"DOP" => ["symbol" => "RD$", 	"decimal_digits" => 2, "code" => "DOP", "name" => "Dominican Peso", "symbol_native" => "RD$", "name_plural" => "Dominican pesos", ],
			"DZD" => ["symbol" => "DA", 	"decimal_digits" => 2, "code" => "DZD", "name" => "Algerian Dinar", "symbol_native" => "د.ج.‏", "name_plural" => "Algerian dinars", ],
			"EEK" => ["symbol" => "Ekr", 	"decimal_digits" => 2, "code" => "EEK", "name" => "Estonian Kroon", "symbol_native" => "kr", "name_plural" => "Estonian kroons", ],
			"EGP" => ["symbol" => "EGP", 	"decimal_digits" => 2, "code" => "EGP", "name" => "Egyptian Pound", "symbol_native" => "ج.م.‏", "name_plural" => "Egyptian pounds", ],
			"ERN" => ["symbol" => "Nfk", 	"decimal_digits" => 2, "code" => "ERN", "name" => "Eritrean Nakfa", "symbol_native" => "Nfk", "name_plural" => "Eritrean nakfas", ],
			"ETB" => ["symbol" => "Br", 	"decimal_digits" => 2, "code" => "ETB", "name" => "Ethiopian Birr", "symbol_native" => "Br", "name_plural" => "Ethiopian birrs", ],
			"GBP" => ["symbol" => "£", 		"decimal_digits" => 2, "code" => "GBP", "name" => "British Pound Sterling", "symbol_native" => "£", "name_plural" => "British pounds sterling", ],
			"GEL" => ["symbol" => "GEL", 	"decimal_digits" => 2, "code" => "GEL", "name" => "Georgian Lari", "symbol_native" => "GEL", "name_plural" => "Georgian laris", ],
			"GHS" => ["symbol" => "GH₵", 	"decimal_digits" => 2, "code" => "GHS", "name" => "Ghanaian Cedi", "symbol_native" => "GH₵", "name_plural" => "Ghanaian cedis", ],
			"GNF" => ["symbol" => "FG", 	"decimal_digits" => 0, "code" => "GNF", "name" => "Guinean Franc", "symbol_native" => "FG", "name_plural" => "Guinean francs", ],
			"GTQ" => ["symbol" => "GTQ", 	"decimal_digits" => 2, "code" => "GTQ", "name" => "Guatemalan Quetzal", "symbol_native" => "Q", "name_plural" => "Guatemalan quetzals", ],
			"HKD" => ["symbol" => "HK$", 	"decimal_digits" => 2, "code" => "HKD", "name" => "Hong Kong Dollar", "symbol_native" => "$", "name_plural" => "Hong Kong dollars", ],
			"HNL" => ["symbol" => "HNL", 	"decimal_digits" => 2, "code" => "HNL", "name" => "Honduran Lempira", "symbol_native" => "L", "name_plural" => "Honduran lempiras", ],
			"HRK" => ["symbol" => "kn", 	"decimal_digits" => 2, "code" => "HRK", "name" => "Croatian Kuna", "symbol_native" => "kn", "name_plural" => "Croatian kunas", ],
			"HUF" => ["symbol" => "Ft", 	"decimal_digits" => 0, "code" => "HUF", "name" => "Hungarian Forint", "symbol_native" => "Ft", "name_plural" => "Hungarian forints", ],
			"IDR" => ["symbol" => "Rp", 	"decimal_digits" => 0, "code" => "IDR", "name" => "Indonesian Rupiah", "symbol_native" => "Rp", "name_plural" => "Indonesian rupiahs", ],
			"ILS" => ["symbol" => "₪", 		"decimal_digits" => 2, "code" => "ILS", "name" => "Israeli New Sheqel", "symbol_native" => "₪", "name_plural" => "Israeli new sheqels", ],
			"INR" => ["symbol" => "Rs", 	"decimal_digits" => 2, "code" => "INR", "name" => "Indian Rupee", "symbol_native" => "টকা", "name_plural" => "Indian rupees", ],
			"IQD" => ["symbol" => "IQD", 	"decimal_digits" => 0, "code" => "IQD", "name" => "Iraqi Dinar", "symbol_native" => "د.ع.‏", "name_plural" => "Iraqi dinars", ],
			"IRR" => ["symbol" => "IRR", 	"decimal_digits" => 0, "code" => "IRR", "name" => "Iranian Rial", "symbol_native" => "﷼", "name_plural" => "Iranian rials", ],
			"ISK" => ["symbol" => "Ikr", 	"decimal_digits" => 0, "code" => "ISK", "name" => "Icelandic Króna", "symbol_native" => "kr", "name_plural" => "Icelandic krónur", ],
			"JMD" => ["symbol" => "J$", 	"decimal_digits" => 2, "code" => "JMD", "name" => "Jamaican Dollar", "symbol_native" => "$", "name_plural" => "Jamaican dollars", ],
			"JOD" => ["symbol" => "JD", 	"decimal_digits" => 3, "code" => "JOD", "name" => "Jordanian Dinar", "symbol_native" => "د.أ.‏", "name_plural" => "Jordanian dinars", ],
			"JPY" => ["symbol" => "¥", 		"decimal_digits" => 0, "code" => "JPY", "name" => "Japanese Yen", "symbol_native" => "￥", "name_plural" => "Japanese yen", ],
			"KES" => ["symbol" => "Ksh", 	"decimal_digits" => 2, "code" => "KES", "name" => "Kenyan Shilling", "symbol_native" => "Ksh", "name_plural" => "Kenyan shillings", ],
			"KHR" => ["symbol" => "KHR", 	"decimal_digits" => 2, "code" => "KHR", "name" => "Cambodian Riel", "symbol_native" => "៛", "name_plural" => "Cambodian riels", ],
			"KMF" => ["symbol" => "CF", 	"decimal_digits" => 0, "code" => "KMF", "name" => "Comorian Franc", "symbol_native" => "FC", "name_plural" => "Comorian francs", ],
			"KRW" => ["symbol" => "₩", 		"decimal_digits" => 0, "code" => "KRW", "name" => "South Korean Won", "symbol_native" => "₩", "name_plural" => "South Korean won", ],
			"KWD" => ["symbol" => "KD", 	"decimal_digits" => 3, "code" => "KWD", "name" => "Kuwaiti Dinar", "symbol_native" => "د.ك.‏", "name_plural" => "Kuwaiti dinars", ],
			"KZT" => ["symbol" => "KZT", 	"decimal_digits" => 2, "code" => "KZT", "name" => "Kazakhstani Tenge", "symbol_native" => "тңг.", "name_plural" => "Kazakhstani tenges", ],
			"LBP" => ["symbol" => "LB£", 	"decimal_digits" => 0, "code" => "LBP", "name" => "Lebanese Pound", "symbol_native" => "ل.ل.‏", "name_plural" => "Lebanese pounds", ],
			"LKR" => ["symbol" => "SLRs", 	"decimal_digits" => 2, "code" => "LKR", "name" => "Sri Lankan Rupee", "symbol_native" => "SL Re", "name_plural" => "Sri Lankan rupees", ],
			"LTL" => ["symbol" => "Lt", 	"decimal_digits" => 2, "code" => "LTL", "name" => "Lithuanian Litas", "symbol_native" => "Lt", "name_plural" => "Lithuanian litai", ],
			"LVL" => ["symbol" => "Ls", 	"decimal_digits" => 2, "code" => "LVL", "name" => "Latvian Lats", "symbol_native" => "Ls", "name_plural" => "Latvian lati", ],
			"LYD" => ["symbol" => "LD", 	"decimal_digits" => 3, "code" => "LYD", "name" => "Libyan Dinar", "symbol_native" => "د.ل.‏", "name_plural" => "Libyan dinars", ],
			"MAD" => ["symbol" => "MAD", 	"decimal_digits" => 2, "code" => "MAD", "name" => "Moroccan Dirham", "symbol_native" => "د.م.‏", "name_plural" => "Moroccan dirhams", ],
			"MDL" => ["symbol" => "MDL", 	"decimal_digits" => 2, "code" => "MDL", "name" => "Moldovan Leu", "symbol_native" => "MDL", "name_plural" => "Moldovan lei", ],
			"MGA" => ["symbol" => "MGA", 	"decimal_digits" => 0, "code" => "MGA", "name" => "Malagasy Ariary", "symbol_native" => "MGA", "name_plural" => "Malagasy Ariaries", ],
			"MKD" => ["symbol" => "MKD", 	"decimal_digits" => 2, "code" => "MKD", "name" => "Macedonian Denar", "symbol_native" => "MKD", "name_plural" => "Macedonian denari", ],
			"MMK" => ["symbol" => "MMK", 	"decimal_digits" => 0, "code" => "MMK", "name" => "Myanma Kyat", "symbol_native" => "K", "name_plural" => "Myanma kyats", ],
			"MOP" => ["symbol" => "MOP$", 	"decimal_digits" => 2, "code" => "MOP", "name" => "Macanese Pataca", "symbol_native" => "MOP$", "name_plural" => "Macanese patacas", ],
			"MUR" => ["symbol" => "MURs", 	"decimal_digits" => 0, "code" => "MUR", "name" => "Mauritian Rupee", "symbol_native" => "MURs", "name_plural" => "Mauritian rupees", ],
			"MXN" => ["symbol" => "MX$", 	"decimal_digits" => 2, "code" => "MXN", "name" => "Mexican Peso", "symbol_native" => "$", "name_plural" => "Mexican pesos", ],
			"MYR" => ["symbol" => "RM", 	"decimal_digits" => 2, "code" => "MYR", "name" => "Malaysian Ringgit", "symbol_native" => "RM", "name_plural" => "Malaysian ringgits", ],
			"MZN" => ["symbol" => "MTn", 	"decimal_digits" => 2, "code" => "MZN", "name" => "Mozambican Metical", "symbol_native" => "MTn", "name_plural" => "Mozambican meticals", ],
			"NAD" => ["symbol" => "N$", 	"decimal_digits" => 2, "code" => "NAD", "name" => "Namibian Dollar", "symbol_native" => "N$", "name_plural" => "Namibian dollars", ],
			"NGN" => ["symbol" => "₦", 		"decimal_digits" => 2, "code" => "NGN", "name" => "Nigerian Naira", "symbol_native" => "₦", "name_plural" => "Nigerian nairas", ],
			"NIO" => ["symbol" => "C$", 	"decimal_digits" => 2, "code" => "NIO", "name" => "Nicaraguan Córdoba", "symbol_native" => "C$", "name_plural" => "Nicaraguan córdobas", ],
			"NOK" => ["symbol" => "Nkr", 	"decimal_digits" => 2, "code" => "NOK", "name" => "Norwegian Krone", "symbol_native" => "kr", "name_plural" => "Norwegian kroner", ],
			"NPR" => ["symbol" => "NPRs", 	"decimal_digits" => 2, "code" => "NPR", "name" => "Nepalese Rupee", "symbol_native" => "नेरू", "name_plural" => "Nepalese rupees", ],
			"NZD" => ["symbol" => "NZ$", 	"decimal_digits" => 2, "code" => "NZD", "name" => "New Zealand Dollar", "symbol_native" => "$", "name_plural" => "New Zealand dollars", ],
			"OMR" => ["symbol" => "OMR", 	"decimal_digits" => 3, "code" => "OMR", "name" => "Omani Rial", "symbol_native" => "ر.ع.‏", "name_plural" => "Omani rials", ],
			"PAB" => ["symbol" => "B/.", 	"decimal_digits" => 2, "code" => "PAB", "name" => "Panamanian Balboa", "symbol_native" => "B/.", "name_plural" => "Panamanian balboas", ],
			"PEN" => ["symbol" => "S/.", 	"decimal_digits" => 2, "code" => "PEN", "name" => "Peruvian Nuevo Sol", "symbol_native" => "S/.", "name_plural" => "Peruvian nuevos soles", ],
			"PHP" => ["symbol" => "₱", 		"decimal_digits" => 2, "code" => "PHP", "name" => "Philippine Peso", "symbol_native" => "₱", "name_plural" => "Philippine pesos", ],
			"PKR" => ["symbol" => "PKRs", 	"decimal_digits" => 0, "code" => "PKR", "name" => "Pakistani Rupee", "symbol_native" => "₨", "name_plural" => "Pakistani rupees", ],
			"PLN" => ["symbol" => "zł", 	"decimal_digits" => 2, "code" => "PLN", "name" => "Polish Zloty", "symbol_native" => "zł", "name_plural" => "Polish zlotys", ],
			"PYG" => ["symbol" => "₲", 		"decimal_digits" => 0, "code" => "PYG", "name" => "Paraguayan Guarani", "symbol_native" => "₲", "name_plural" => "Paraguayan guaranis", ],
			"QAR" => ["symbol" => "QR", 	"decimal_digits" => 2, "code" => "QAR", "name" => "Qatari Rial", "symbol_native" => "ر.ق.‏", "name_plural" => "Qatari rials", ],
			"RON" => ["symbol" => "RON", 	"decimal_digits" => 2, "code" => "RON", "name" => "Romanian Leu", "symbol_native" => "RON", "name_plural" => "Romanian lei", ],
			"RSD" => ["symbol" => "din.", 	"decimal_digits" => 0, "code" => "RSD", "name" => "Serbian Dinar", "symbol_native" => "дин.", "name_plural" => "Serbian dinars", ],
			"RUB" => ["symbol" => "RUB", 	"decimal_digits" => 2, "code" => "RUB", "name" => "Russian Ruble", "symbol_native" => "руб.", "name_plural" => "Russian rubles", ],
			"RWF" => ["symbol" => "RWF", 	"decimal_digits" => 0, "code" => "RWF", "name" => "Rwandan Franc", "symbol_native" => "FR", "name_plural" => "Rwandan francs", ],
			"SAR" => ["symbol" => "SR", 	"decimal_digits" => 2, "code" => "SAR", "name" => "Saudi Riyal", "symbol_native" => "ر.س.‏", "name_plural" => "Saudi riyals", ],
			"SDG" => ["symbol" => "SDG", 	"decimal_digits" => 2, "code" => "SDG", "name" => "Sudanese Pound", "symbol_native" => "SDG", "name_plural" => "Sudanese pounds", ],
			"SEK" => ["symbol" => "Skr", 	"decimal_digits" => 2, "code" => "SEK", "name" => "Swedish Krona", "symbol_native" => "kr", "name_plural" => "Swedish kronor", ],
			"SGD" => ["symbol" => "S$", 	"decimal_digits" => 2, "code" => "SGD", "name" => "Singapore Dollar", "symbol_native" => "$", "name_plural" => "Singapore dollars", ],
			"SOS" => ["symbol" => "Ssh", 	"decimal_digits" => 0, "code" => "SOS", "name" => "Somali Shilling", "symbol_native" => "Ssh", "name_plural" => "Somali shillings", ],
			"SYP" => ["symbol" => "SY£", 	"decimal_digits" => 0, "code" => "SYP", "name" => "Syrian Pound", "symbol_native" => "ل.س.‏", "name_plural" => "Syrian pounds", ],
			"THB" => ["symbol" => "฿", 		"decimal_digits" => 2, "code" => "THB", "name" => "Thai Baht", "symbol_native" => "฿", "name_plural" => "Thai baht", ],
			"TND" => ["symbol" => "DT", 	"decimal_digits" => 3, "code" => "TND", "name" => "Tunisian Dinar", "symbol_native" => "د.ت.‏", "name_plural" => "Tunisian dinars", ],
			"TOP" => ["symbol" => "T$", 	"decimal_digits" => 2, "code" => "TOP", "name" => "Tongan Paʻanga", "symbol_native" => "T$", "name_plural" => "Tongan paʻanga", ],
			"TRY" => ["symbol" => "TL", 	"decimal_digits" => 2, "code" => "TRY", "name" => "Turkish Lira", "symbol_native" => "TL", "name_plural" => "Turkish Lira", ],
			"TTD" => ["symbol" => "TT$", 	"decimal_digits" => 2, "code" => "TTD", "name" => "Trinidad and Tobago Dollar", "symbol_native" => "$", "name_plural" => "Trinidad and Tobago dollars", ],
			"TWD" => ["symbol" => "NT$", 	"decimal_digits" => 2, "code" => "TWD", "name" => "New Taiwan Dollar", "symbol_native" => "NT$", "name_plural" => "New Taiwan dollars", ],
			"TZS" => ["symbol" => "TSh", 	"decimal_digits" => 0, "code" => "TZS", "name" => "Tanzanian Shilling", "symbol_native" => "TSh", "name_plural" => "Tanzanian shillings", ],
			"UAH" => ["symbol" => "₴", 		"decimal_digits" => 2, "code" => "UAH", "name" => "Ukrainian Hryvnia", "symbol_native" => "₴", "name_plural" => "Ukrainian hryvnias", ],
			"UGX" => ["symbol" => "USh", 	"decimal_digits" => 0, "code" => "UGX", "name" => "Ugandan Shilling", "symbol_native" => "USh", "name_plural" => "Ugandan shillings", ],
			"UYU" => ["symbol" => "$U", 	"decimal_digits" => 2, "code" => "UYU", "name" => "Uruguayan Peso", "symbol_native" => "$", "name_plural" => "Uruguayan pesos", ],
			"UZS" => ["symbol" => "UZS", 	"decimal_digits" => 0, "code" => "UZS", "name" => "Uzbekistan Som", "symbol_native" => "UZS", "name_plural" => "Uzbekistan som", ],
			"VEF" => ["symbol" => "Bs.F.", 	"decimal_digits" => 2, "code" => "VEF", "name" => "Venezuelan Bolívar", "symbol_native" => "Bs.F.", "name_plural" => "Venezuelan bolívars", ],
			"VND" => ["symbol" => "₫", 		"decimal_digits" => 0, "code" => "VND", "name" => "Vietnamese Dong", "symbol_native" => "₫", "name_plural" => "Vietnamese dong", ],
			"XAF" => ["symbol" => "FCFA", 	"decimal_digits" => 0, "code" => "XAF", "name" => "CFA Franc BEAC", "symbol_native" => "FCFA", "name_plural" => "CFA francs BEAC", ],
			"XOF" => ["symbol" => "CFA", 	"decimal_digits" => 0, "code" => "XOF", "name" => "CFA Franc BCEAO", "symbol_native" => "CFA", "name_plural" => "CFA francs BCEAO", ],
			"YER" => ["symbol" => "YR", 	"decimal_digits" => 0, "code" => "YER", "name" => "Yemeni Rial", "symbol_native" => "ر.ي.‏", "name_plural" => "Yemeni rials", ],
			"ZAR" => ["symbol" => "R", 		"decimal_digits" => 2, "code" => "ZAR", "name" => "South African Rand", "symbol_native" => "R", "name_plural" => "South African rand", ],
			"ZMK" => ["symbol" => "ZK", 	"decimal_digits" => 0, "code" => "ZMK", "name" => "Zambian Kwacha", "symbol_native" => "ZK", "name_plural" => "Zambian kwachas", ],
		];

		return $currncy;
	}
}
?>
