ALTER TABLE jibres_XXXXXXX.products ADD `bullet` text CHARACTER SET utf8mb4 NULL DEFAULT NULL AFTER `desc`;
ALTER TABLE jibres_XXXXXXX.products ADD `title2` VARCHAR(300) CHARACTER SET utf8mb4 NULL DEFAULT NULL AFTER `title`;
