ALTER TABLE jibres_XXXXXXX.logs CHANGE `ip` `ip` BIGINT(20) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.sessions CHANGE `ip` `ip` BIGINT(20) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.comments CHANGE `ip` `ip` BIGINT(20) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.tickets CHANGE `ip` `ip` BIGINT(20) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.visitors CHANGE `visitor_ip` `visitor_ip` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE jibres_XXXXXXX.productcomment CHANGE `ip` `ip` BIGINT(20) NULL DEFAULT NULL;

ALTER TABLE jibres_XXXXXXX.files CHANGE `ip` `ip` BIGINT(20) NULL DEFAULT NULL;
