CREATE TABLE IF NOT EXISTS jibres_XXXXXXX.userlegal (
`user_id` INT(10) UNSIGNED NOT NULL,
`companyname` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`companyeconomiccode` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`companynationalid` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`companyregisternumber` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`ceonationalcode` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
`country` char(2) CHARACTER SET utf8mb4 DEFAULT NULL,
`province` varchar(6) CHARACTER SET utf8mb4 DEFAULT NULL,
`city` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`address` varchar(500) CHARACTER SET utf8mb4 DEFAULT NULL,
`address2` varchar(500) CHARACTER SET utf8mb4 DEFAULT NULL,
`postcode` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
`phone` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
`mobile` varchar(20) DEFAULT NULL,
`fax` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
`latitude` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`longitude` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
`map` text CHARACTER SET utf8mb4,
`datecreated` timestamp NULL,
`datemodified` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`user_id`),
CONSTRAINT `customerlegal_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
