CREATE TABLE IF NOT EXISTS jibres_XXXXXXX.tax_coding (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`code` int(10) NULL,
`title` varchar(200) NULL,
`parent1` int(10) UNSIGNED NULL,
`parent2` int(10) UNSIGNED NULL,
`parent3` int(10) UNSIGNED NULL,
`status` enum('enable','disable', 'deleted') DEFAULT NULL,
`nature` enum('debtor','creditor','debtor-creditor','balance sheet','disciplinary','harmful profit') DEFAULT NULL,
`detailable` bit(1)  NULL,
`type` enum('group','total','assistant','details') DEFAULT NULL,
`datecreated` timestamp NULL ,
`datemodified` timestamp NULL ,
PRIMARY KEY (`id`),
KEY `tax_coding_search_index_parent1` (`parent1`),
KEY `tax_coding_search_index_parent2` (`parent2`),
KEY `tax_coding_search_index_parent3` (`parent3`),
KEY `tax_coding_search_index_code` (`code`),
KEY `tax_coding_search_index_title` (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
