ALTER TABLE jibres_XXXXXXX.tax_coding CHANGE `topic` `topic` enum (
'net sales',
'accumulated profit',
'orders and prepayments',
'short term investments',
'wealth',
'other non-operating expenses',
'other operating costs',
'other operating income',
'other accounts and documents receivable',
'other accounts and documents payable',
'save employee end-of-service benefits',
'save taxes',
'tangible fixed assets',
'accounts receivable and commercial documents',
'business accounts and documents payable',
'receivables',
'prepayments',
'long-term accounts and documents',
'cash balance',
'received financial facilities',
'administrative costs',
'sales costs',
'financial costs',
'general expenses',
'intangible fixed assets'
) NULL DEFAULT NULL;