ALTER TABLE jibres_XXXXXXX.form_tag ADD `form_id` INT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.form_tag ADD CONSTRAINT `form_tag_form_id` FOREIGN KEY (`form_id`) REFERENCES `form` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
