ALTER TABLE jibres_XXXXXXX.dayevent ADD `countcalc2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `dbtrafic2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `dbsize2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `activeuser2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `deactiveuser2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `log2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `visitor2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `agent2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `session2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `urls2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `ticket2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `comment2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `address2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `news2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `page2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `post2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `transaction2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `term2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `termusages2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `datecreated2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `datemodified2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `help2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `attachment2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `tag2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `cat2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `support_tag2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `help_tag2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_mobile2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_email2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_chatid2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_username2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_android2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_awaiting2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_removed2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_filter2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_unreachabl2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_permission2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `ticket_message2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `userdetail2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `lastactivity2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `lastchangesetting2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `lastadminlogin2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `laststafflogin2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `lastsale2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `lastbuy2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `customer2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `staff2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `sumplustransaction2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `summinustransaction2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `product2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `factor2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `factorbuy2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `factorsale2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `factordetail2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `sumfactor2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `planhistory2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `cart2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `sync2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `apilog2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `app_download2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `csrf2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `dayevent2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `factoraction2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `factoraddress2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `files2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `fileusage2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form_answer2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form_answerdetail2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form_choice2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form_filter2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form_filter_where2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `form_item2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `funds2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `importexport2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `inventory2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `ir_vat2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `log_notif2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `login2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `login_ip2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `pos2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productcategory2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productcategoryusage2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productcomment2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productcompany2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productinventory2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productprices2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productproperties2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `producttag2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `producttagusage2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `productunit2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `setting2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `tax_coding2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `tax_docdetail2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `tax_document2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `tax_year2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `telegrams2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_auth2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `user_telegram2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `userlegal2` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent ADD `visitors2` DECIMAL(22, 4) NULL DEFAULT NULL;


UPDATE jibres_XXXXXXX.dayevent SET `countcalc2`            = CAST(dayevent.countcalc AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `dbtrafic2`             = CAST(dayevent.dbtrafic AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `dbsize2`               = CAST(dayevent.dbsize AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user2`                 = CAST(dayevent.user AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `activeuser2`           = CAST(dayevent.activeuser AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `deactiveuser2`         = CAST(dayevent.deactiveuser AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `log2`                  = CAST(dayevent.log AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `visitor2`              = CAST(dayevent.visitor AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `agent2`                = CAST(dayevent.agent AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `session2`              = CAST(dayevent.session AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `urls2`                 = CAST(dayevent.urls AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `ticket2`               = CAST(dayevent.ticket AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `comment2`              = CAST(dayevent.comment AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `address2`              = CAST(dayevent.address AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `news2`                 = CAST(dayevent.news AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `page2`                 = CAST(dayevent.page AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `post2`                 = CAST(dayevent.post AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `transaction2`          = CAST(dayevent.transaction AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `term2`                 = CAST(dayevent.term AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `termusages2`           = CAST(dayevent.termusages AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `datecreated2`          = CAST(dayevent.datecreated AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `datemodified2`         = CAST(dayevent.datemodified AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `help2`                 = CAST(dayevent.help AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `attachment2`           = CAST(dayevent.attachment AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `tag2`                  = CAST(dayevent.tag AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `cat2`                  = CAST(dayevent.cat AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `support_tag2`          = CAST(dayevent.support_tag AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `help_tag2`             = CAST(dayevent.help_tag AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_mobile2`          = CAST(dayevent.user_mobile AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_email2`           = CAST(dayevent.user_email AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_chatid2`          = CAST(dayevent.user_chatid AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_username2`        = CAST(dayevent.user_username AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_android2`         = CAST(dayevent.user_android AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_awaiting2`        = CAST(dayevent.user_awaiting AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_removed2`         = CAST(dayevent.user_removed AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_filter2`          = CAST(dayevent.user_filter AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_unreachabl2`      = CAST(dayevent.user_unreachabl AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_permission2`      = CAST(dayevent.user_permission AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `ticket_message2`       = CAST(dayevent.ticket_message AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `userdetail2`           = CAST(dayevent.userdetail AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `lastactivity2`         = CAST(dayevent.lastactivity AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `lastchangesetting2`    = CAST(dayevent.lastchangesetting AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `lastadminlogin2`       = CAST(dayevent.lastadminlogin AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `laststafflogin2`       = CAST(dayevent.laststafflogin AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `lastsale2`             = CAST(dayevent.lastsale AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `lastbuy2`              = CAST(dayevent.lastbuy AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `customer2`             = CAST(dayevent.customer AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `staff2`                = CAST(dayevent.staff AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `sumplustransaction2`   = CAST(dayevent.sumplustransaction AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `summinustransaction2`  = CAST(dayevent.summinustransaction AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `product2`              = CAST(dayevent.product AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `factor2`               = CAST(dayevent.factor AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `factorbuy2`            = CAST(dayevent.factorbuy AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `factorsale2`           = CAST(dayevent.factorsale AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `factordetail2`         = CAST(dayevent.factordetail AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `sumfactor2`            = CAST(dayevent.sumfactor AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `planhistory2`          = CAST(dayevent.planhistory AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `cart2`                 = CAST(dayevent.cart AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `sync2`                 = CAST(dayevent.sync AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `apilog2`               = CAST(dayevent.apilog AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `app_download2`         = CAST(dayevent.app_download AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `csrf2`                 = CAST(dayevent.csrf AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `dayevent2`             = CAST(dayevent.dayevent AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `factoraction2`         = CAST(dayevent.factoraction AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `factoraddress2`        = CAST(dayevent.factoraddress AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `files2`                = CAST(dayevent.files AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `fileusage2`            = CAST(dayevent.fileusage AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form2`                 = CAST(dayevent.form AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form_answer2`          = CAST(dayevent.form_answer AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form_answerdetail2`    = CAST(dayevent.form_answerdetail AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form_choice2`          = CAST(dayevent.form_choice AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form_filter2`          = CAST(dayevent.form_filter AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form_filter_where2`    = CAST(dayevent.form_filter_where AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `form_item2`            = CAST(dayevent.form_item AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `funds2`                = CAST(dayevent.funds AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `importexport2`         = CAST(dayevent.importexport AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `inventory2`            = CAST(dayevent.inventory AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `ir_vat2`               = CAST(dayevent.ir_vat AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `log_notif2`            = CAST(dayevent.log_notif AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `login2`                = CAST(dayevent.login AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `login_ip2`             = CAST(dayevent.login_ip AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `pos2`                  = CAST(dayevent.pos AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productcategory2`      = CAST(dayevent.productcategory AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productcategoryusage2` = CAST(dayevent.productcategoryusage AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productcomment2`       = CAST(dayevent.productcomment AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productcompany2`       = CAST(dayevent.productcompany AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productinventory2`     = CAST(dayevent.productinventory AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productprices2`        = CAST(dayevent.productprices AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productproperties2`    = CAST(dayevent.productproperties AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `producttag2`           = CAST(dayevent.producttag AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `producttagusage2`      = CAST(dayevent.producttagusage AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `productunit2`          = CAST(dayevent.productunit AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `setting2`              = CAST(dayevent.setting AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `tax_coding2`           = CAST(dayevent.tax_coding AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `tax_docdetail2`        = CAST(dayevent.tax_docdetail AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `tax_document2`         = CAST(dayevent.tax_document AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `tax_year2`             = CAST(dayevent.tax_year AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `telegrams2`            = CAST(dayevent.telegrams AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_auth2`            = CAST(dayevent.user_auth AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `user_telegram2`        = CAST(dayevent.user_telegram AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `userlegal2`            = CAST(dayevent.userlegal AS DECIMAL(22, 4));
UPDATE jibres_XXXXXXX.dayevent SET `visitors2`             = CAST(dayevent.visitors AS DECIMAL(22, 4));

ALTER TABLE jibres_XXXXXXX.dayevent DROP `countcalc`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `dbtrafic`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `dbsize`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `activeuser`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `deactiveuser`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `log`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `visitor`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `agent`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `session`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `urls`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `ticket`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `comment`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `address`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `news`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `page`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `post`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `transaction`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `term`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `termusages`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `datecreated`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `datemodified`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `help`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `attachment`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `tag`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `cat`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `support_tag`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `help_tag`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_mobile`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_email`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_chatid`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_username`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_android`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_awaiting`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_removed`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_filter`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_unreachabl`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_permission`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `ticket_message`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `userdetail`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `lastactivity`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `lastchangesetting`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `lastadminlogin`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `laststafflogin`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `lastsale`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `lastbuy`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `customer`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `staff`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `sumplustransaction`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `summinustransaction`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `product`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `factor`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `factorbuy`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `factorsale`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `factordetail`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `sumfactor`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `planhistory`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `cart`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `sync`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `apilog`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `app_download`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `csrf`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `dayevent`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `factoraction`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `factoraddress`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `files`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `fileusage`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form_answer`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form_answerdetail`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form_choice`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form_filter`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form_filter_where`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `form_item`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `funds`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `importexport`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `inventory`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `ir_vat`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `log_notif`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `login`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `login_ip`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `pos`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productcategory`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productcategoryusage`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productcomment`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productcompany`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productinventory`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productprices`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productproperties`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `producttag`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `producttagusage`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `productunit`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `setting`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `tax_coding`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `tax_docdetail`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `tax_document`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `tax_year`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `telegrams`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_auth`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `user_telegram`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `userlegal`;
ALTER TABLE jibres_XXXXXXX.dayevent DROP `visitors`;



ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `countcalc2` `countcalc` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `dbtrafic2` `dbtrafic` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `dbsize2` `dbsize` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user2` `user` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `activeuser2` `activeuser` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `deactiveuser2` `deactiveuser` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `log2` `log` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `visitor2` `visitor` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `agent2` `agent` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `session2` `session` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `urls2` `urls` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `ticket2` `ticket` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `comment2` `comment` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `address2` `address` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `news2` `news` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `page2` `page` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `post2` `post` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `transaction2` `transaction` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `term2` `term` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `termusages2` `termusages` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `datecreated2` `datecreated` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `datemodified2` `datemodified` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `help2` `help` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `attachment2` `attachment` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `tag2` `tag` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `cat2` `cat` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `support_tag2` `support_tag` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `help_tag2` `help_tag` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_mobile2` `user_mobile` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_email2` `user_email` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_chatid2` `user_chatid` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_username2` `user_username` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_android2` `user_android` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_awaiting2` `user_awaiting` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_removed2` `user_removed` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_filter2` `user_filter` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_unreachabl2` `user_unreachabl` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_permission2` `user_permission` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `ticket_message2` `ticket_message` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `userdetail2` `userdetail` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `lastactivity2` `lastactivity` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `lastchangesetting2` `lastchangesetting` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `lastadminlogin2` `lastadminlogin` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `laststafflogin2` `laststafflogin` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `lastsale2` `lastsale` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `lastbuy2` `lastbuy` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `customer2` `customer` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `staff2` `staff` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `sumplustransaction2` `sumplustransaction` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `summinustransaction2` `summinustransaction` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `product2` `product` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `factor2` `factor` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `factorbuy2` `factorbuy` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `factorsale2` `factorsale` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `factordetail2` `factordetail` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `sumfactor2` `sumfactor` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `planhistory2` `planhistory` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `cart2` `cart` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `sync2` `sync` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `apilog2` `apilog` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `app_download2` `app_download` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `csrf2` `csrf` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `dayevent2` `dayevent` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `factoraction2` `factoraction` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `factoraddress2` `factoraddress` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `files2` `files` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `fileusage2` `fileusage` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form2` `form` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form_answer2` `form_answer` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form_answerdetail2` `form_answerdetail` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form_choice2` `form_choice` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form_filter2` `form_filter` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form_filter_where2` `form_filter_where` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `form_item2` `form_item` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `funds2` `funds` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `importexport2` `importexport` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `inventory2` `inventory` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `ir_vat2` `ir_vat` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `log_notif2` `log_notif` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `login2` `login` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `login_ip2` `login_ip` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `pos2` `pos` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productcategory2` `productcategory` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productcategoryusage2` `productcategoryusage` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productcomment2` `productcomment` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productcompany2` `productcompany` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productinventory2` `productinventory` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productprices2` `productprices` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productproperties2` `productproperties` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `producttag2` `producttag` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `producttagusage2` `producttagusage` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `productunit2` `productunit` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `setting2` `setting` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `tax_coding2` `tax_coding` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `tax_docdetail2` `tax_docdetail` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `tax_document2` `tax_document` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `tax_year2` `tax_year` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `telegrams2` `telegrams` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_auth2` `user_auth` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `user_telegram2` `user_telegram` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `userlegal2` `userlegal` DECIMAL(22, 4) NULL DEFAULT NULL;
ALTER TABLE jibres_XXXXXXX.dayevent CHANGE `visitors2` `visitors` DECIMAL(22, 4) NULL DEFAULT NULL;
