CREATE TABLE IF NOT EXISTS jibres_XXXXXXX.sms_log (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`provider` varchar(50) NULL DEFAULT NULL,
`mobile` varchar(50) NULL DEFAULT NULL,
`mobiles` text NULL DEFAULT NULL,
`message` text NULL DEFAULT NULL,
`len` int(10) NULL DEFAULT NULL,
`cost` decimal(13, 4) NULL DEFAULT NULL,
`amount` decimal(13, 4) NULL DEFAULT NULL,
`mode` enum('sms', 'call','tts') NULL,
`type` enum('signup', 'login','twostep', 'twostepset', 'twostepunset', 'deleteaccount', 'recovermobile', 'callback_signup', 'changepassword', 'notif', 'other') NULL,
`status` enum('send', 'delivered','queue', 'failed', 'undelivered', 'cancel', 'block', 'other') NULL,
`user_id` int(10) UNSIGNED NULL,
`url` text NULL,
`urlmd5` CHAR(32) NULL,
`ip` VARCHAR(200) NULL,
`ip_id` int(10) UNSIGNED NULL,
`agent_id` int(10) UNSIGNED NULL,
`line` varchar(100) NULL DEFAULT NULL,
`apikey` text NULL DEFAULT NULL,
`response` text NULL DEFAULT NULL,
`send` text NULL DEFAULT NULL,
`datesend` timestamp NULL,
`dateresponse` timestamp NULL,
`datecreated` timestamp NULL,
`datemodified` timestamp NULL,
PRIMARY KEY (`id`),
KEY `smslog_cost` (`cost`),
KEY `smslog_amount` (`amount`),
KEY `smslog_status` (`status`),
KEY `smslog_mobile` (`mobile`),
KEY `smslog_urlmd5` (`urlmd5`),
KEY `smslog_mode` (`mode`),
KEY `smslog_len` (`len`),
KEY `smslog_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;