CREATE TABLE jibres_XXXXXXX.pagebuilder (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`platform` ENUM('website', 'android', 'ios', 'pwa') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`mode` ENUM('header', 'footer', 'body') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`related` ENUM('homepage', 'posts', 'products', 'terms', 'hashtags', 'tags') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`related_id` bigint DEFAULT NULL,
`duplicate` int(10) UNSIGNED DEFAULT NULL,
`title` varchar(500) DEFAULT NULL,
`titlesetting` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`background` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`avand` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`margin` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`padding` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`radius` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`meta` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`sort` int(10) DEFAULT NULL,
`status` ENUM('draft','enable','disable','deleted') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`ifloginshow` ENUM('yes','no') CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`ifpermissionshow` varchar(100) CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`type` varchar(100) CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`puzzle` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`infoposition` text CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`detail` mediumtext CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`text` mediumtext CHARACTER SET utf8mb4 NULL DEFAULT NULL,
`datecreated` timestamp NULL DEFAULT NULL,
`datemodified` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `index_search_pagebuilder_platform` (`platform`),
KEY `index_search_pagebuilder_mode` (`mode`),
KEY `index_search_pagebuilder_related` (`related`),
KEY `index_search_pagebuilder_related_id` (`related_id`),
KEY `index_search_pagebuilder_title` (`title`),
KEY `index_search_pagebuilder_sort` (`sort`),
KEY `index_search_pagebuilder_type` (`type`),
KEY `index_search_pagebuilder_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;