ALTER TABLE jibres_XXXXXXX.apilog ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.apilog ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.app_download ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.app_download ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.cart ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.cart ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.comments ADD `ip_id` BIGINT UNSIGNED NULL AFTER `ip`;

ALTER TABLE jibres_XXXXXXX.csrf ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.csrf ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.email_log CHANGE `ip_id` `ip_id` BIGINT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.factors ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.factors ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.files ADD `ip_id` BIGINT UNSIGNED NULL AFTER `ip`;
ALTER TABLE jibres_XXXXXXX.files ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.form_answer ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.form_answer ADD `agent_id` INT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.login CHANGE `ip_id` `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.login_ip CHANGE `ip_id` `ip_id` BIGINT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.logs ADD `ip_id` BIGINT UNSIGNED NULL AFTER `ip`;
ALTER TABLE jibres_XXXXXXX.logs ADD `agent_id` INT UNSIGNED NULL AFTER `ip_id`;

ALTER TABLE jibres_XXXXXXX.sms_log CHANGE `ip_id` `ip_id` BIGINT UNSIGNED NULL;

ALTER TABLE jibres_XXXXXXX.tickets ADD `ip_id` BIGINT UNSIGNED NULL AFTER `ip`;

ALTER TABLE jibres_XXXXXXX.transactions ADD `ip_id` BIGINT UNSIGNED NULL;
ALTER TABLE jibres_XXXXXXX.transactions ADD `agent_id` INT UNSIGNED NULL;
