DROP TABLE IF EXISTS jibres_XXXXXXX.email_log ;

CREATE TABLE jibres_XXXXXXX.crm_email (
`id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
`provider` varchar(50) DEFAULT NULL,
`from` varchar(200) DEFAULT NULL,
`to` varchar(200) DEFAULT NULL,
`subject` varchar(200) DEFAULT NULL,
`design` varchar(100) DEFAULT NULL,
`body` text,
`template` varchar(100) DEFAULT NULL,
`status` enum('pending', 'sending', 'send', 'sended', 'delivered','queue','failed','undelivered','cancel','block','other') DEFAULT NULL,
`user_id` int UNSIGNED DEFAULT NULL,
`ip_id` BIGINT UNSIGNED NULL,
`agent_id` int UNSIGNED DEFAULT NULL,
`response` text,
`datesend` timestamp NULL DEFAULT NULL,
`dateresponse` timestamp NULL DEFAULT NULL,
`datecreated` timestamp NULL DEFAULT NULL,
`datemodified` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `crm_email_status` (`status`),
KEY `crm_email_template` (`template`),
KEY `crm_email_from` (`from`),
KEY `crm_email_to` (`to`),
KEY `crm_email_subject` (`subject`),
KEY `crm_email_datecreated` (`datecreated`),
KEY `crm_email_ip_id` (`ip_id`),
KEY `crm_email_agent_id` (`agent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
