CREATE TABLE `storetransactions` (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`code` varchar(200) NULL,
`title` text NULL DEFAULT NULL,
`type` varchar(100) NULL DEFAULT NULL,
`store_id` int(10) UNSIGNED NOT NULL,
`userstore_id` bigint(20) UNSIGNED NULL,
`operator` bigint(20) UNSIGNED NOT NULL,
`fund_id` int(10) UNSIGNED DEFAULT NULL,
`factor_id` bigint(20) UNSIGNED DEFAULT NULL,
`plus` bigint(20) UNSIGNED DEFAULT NULL,
`minus` bigint(20) UNSIGNED DEFAULT NULL,
`unit_id` smallint(3) NOT NULL,
`date` datetime DEFAULT NULL,
`verify` bit(1) NULL DEFAULT NULL,
`duedate` datetime DEFAULT NULL,
`status` enum('enable','disable','deleted','expired','awaiting','filtered','blocked','spam') NOT NULL DEFAULT 'enable',
`parent_id` bigint(20) UNSIGNED NULL DEFAULT NULL,
`datecreated` timestamp DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
CONSTRAINT `storetransaction_store_id` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON UPDATE CASCADE,
CONSTRAINT `storetransaction_userstore_id` FOREIGN KEY (`userstore_id`) REFERENCES `userstores` (`id`) ON UPDATE CASCADE,
CONSTRAINT `storetransaction_fund_id` FOREIGN KEY (`fund_id`) REFERENCES `funds` (`id`) ON UPDATE CASCADE,
CONSTRAINT `storetransaction_factor_id` FOREIGN KEY (`factor_id`) REFERENCES `factors` (`id`) ON UPDATE CASCADE,
CONSTRAINT `storetransaction_operator_id` FOREIGN KEY (`operator`) REFERENCES `userstores` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;