CREATE TABLE `store_analytics` (
`id` int(10) UNSIGNED NOT NULL,
`lastactivity` timestamp NULL DEFAULT NULL,
`dbtrafic` int(10) UNSIGNED DEFAULT NULL,
`dbsize` int(10) UNSIGNED DEFAULT NULL,
`users` int(10) UNSIGNED DEFAULT NULL,
`activeuser` int(10) UNSIGNED DEFAULT NULL,
`deactiveuser` int(10) UNSIGNED DEFAULT NULL,
`log` int(10) UNSIGNED DEFAULT NULL,
`visitor` int(10) UNSIGNED DEFAULT NULL,
`agent` int(10) UNSIGNED DEFAULT NULL,
`session` int(10) UNSIGNED DEFAULT NULL,
`ticket` int(10) UNSIGNED DEFAULT NULL,
`ticket_message` int(10) UNSIGNED DEFAULT NULL,
`comment` int(10) UNSIGNED DEFAULT NULL,
`address` int(10) UNSIGNED DEFAULT NULL,
`news` int(10) UNSIGNED DEFAULT NULL,
`page` int(10) UNSIGNED DEFAULT NULL,
`post` int(10) UNSIGNED DEFAULT NULL,
`transaction` int(10) UNSIGNED DEFAULT NULL,
`term` int(10) UNSIGNED DEFAULT NULL,
`termusages` int(10) UNSIGNED DEFAULT NULL,
`storetransaction` int(10) UNSIGNED DEFAULT NULL,
`sumplustransaction` int(10) UNSIGNED DEFAULT NULL,
`summinustransaction` int(10) UNSIGNED DEFAULT NULL,
`product` int(10) UNSIGNED DEFAULT NULL,
`factor` int(10) UNSIGNED DEFAULT NULL,
`factordetail` int(10) UNSIGNED DEFAULT NULL,
`sumfactor` int(10) UNSIGNED DEFAULT NULL,
`planhistory` int(10) UNSIGNED DEFAULT NULL,
`help` int(10) UNSIGNED DEFAULT NULL,
`attachment` int(10) UNSIGNED DEFAULT NULL,
`tag` int(10) UNSIGNED DEFAULT NULL,
`cat` int(10) UNSIGNED DEFAULT NULL,
`support_tag` int(10) UNSIGNED DEFAULT NULL,
`help_tag` int(10) UNSIGNED DEFAULT NULL,
`user_mobile` int(10) UNSIGNED DEFAULT NULL,
`user_email` int(10) UNSIGNED DEFAULT NULL,
`user_chatid` int(10) UNSIGNED DEFAULT NULL,
`user_username` int(10) UNSIGNED DEFAULT NULL,
`user_android` int(10) UNSIGNED DEFAULT NULL,
`user_awaiting` int(10) UNSIGNED DEFAULT NULL,
`user_removed` int(10) UNSIGNED DEFAULT NULL,
`user_filter` int(10) UNSIGNED DEFAULT NULL,
`user_unreachabl` int(10) UNSIGNED DEFAULT NULL,
`user_permission` int(10) UNSIGNED DEFAULT NULL,
`datecreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(`id`),
CONSTRAINT `store_analytics_id` FOREIGN KEY (`id`) REFERENCES `store` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
