CREATE TABLE products (
`id`					int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`store_id`				int(10) UNSIGNED NOT NULL,
`creator`				int(10) UNSIGNED NOT NULL,
`title`					varchar(500) NOT NULL,
`name`					varchar(200) NULL DEFAULT NULL,
`cat`					varchar(200) NULL DEFAULT NULL,
`slug`					varchar(200) NULL DEFAULT NULL,
`company`				varchar(200) NULL DEFAULT NULL,
`shortcode`				int(10) NULL DEFAULT NULL,
`unit`					varchar(100) NULL DEFAULT NULL,
`barcode`				varchar(100) NULL DEFAULT NULL,
`barcode2`				varchar(100) NULL DEFAULT NULL,
`code`					varchar(100) NULL DEFAULT NULL,
`buyprice`				BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`price`					BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`discount`				BIGINT(20) NULL DEFAULT NULL,
`discountpercent`		smallint(3) NULL DEFAULT NULL,
`vat`					BIT(1) NULL DEFAULT NULL,
`initialbalance`		float(10) UNSIGNED NULL DEFAULT NULL,
`minstock`				float(10) UNSIGNED NULL DEFAULT NULL,
`maxstock`				float(10) UNSIGNED NULL DEFAULT NULL,
`status`				enum('unset', 'available', 'unavailable', 'soon', 'discountinued') NULL DEFAULT NULL,
`sold`					BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`stock`					BIGINT(20) UNSIGNED NULL DEFAULT NULL,
`thumb`					varchar(2000) NULL DEFAULT NULL,
`service`				BIT(1) NULL DEFAULT NULL,
`checkstock`			BIT(1) NULL DEFAULT NULL,
`sellonline`			BIT(1) NULL DEFAULT NULL,
`sellstore`				BIT(1) NULL DEFAULT NULL,
`carton`				float(10) UNSIGNED NULL DEFAULT NULL,
`datecreated` 			timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`datemodified` 			timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc`					text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
PRIMARY KEY (`id`),
CONSTRAINT `products_creator` FOREIGN KEY (`creator`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
CONSTRAINT `products_store_id` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
