CREATE TABLE `factors` (
`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`store_id` int(10) UNSIGNED NOT NULL,
`customer` bigint(20) UNSIGNED NULL,
`seller` bigint(20) UNSIGNED NOT NULL,
`date` datetime NOT NULL,
`shamsidate` int(10) UNSIGNED NOT NULL,
`title` varchar(500) NULL,
`pre` bit(1) DEFAULT NULL,
`transport` bigint(20) UNSIGNED DEFAULT NULL,
`pay` bit(1) DEFAULT NULL,
`detailsum` bigint(20) UNSIGNED DEFAULT NULL,
`detaildiscount` bigint(20) DEFAULT NULL,
`detailtotalsum` bigint(20) UNSIGNED DEFAULT NULL,
`detailcount` smallint(5) UNSIGNED DEFAULT NULL,
`vat` int(10) UNSIGNED DEFAULT NULL,
`discount` int(10) DEFAULT NULL,
`sum` bigint(20) UNSIGNED DEFAULT NULL,
`status` enum('enable','disable','expire') NOT NULL DEFAULT 'enable',
`datecreated` datetime DEFAULT CURRENT_TIMESTAMP,
`datemodified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
`desc` text CHARACTER SET utf8mb4,
PRIMARY KEY (`id`),
CONSTRAINT `factors_customer` FOREIGN KEY (`seller`) REFERENCES `userstores` (`id`) ON UPDATE CASCADE,
CONSTRAINT `factors_seller` FOREIGN KEY (`customer`) REFERENCES `userstores` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

